import { Product } from "./Product";

export const AllProducts: Product[] = [
  {
    id: 1,
    name: 'Kids T-Shirt',
    color: '#EDE580',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!A bright #EDE580 t-shirt for kids.',
    type: 'T-Shirt',
    category: 'Kids',
    price: 15.99,
    fabric: 'Cotton',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Breathable', 'Machine washable'],
    availableColors: ['#EDE580', '#983628', '#A3BBAD'],
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: 2,
    name: 'Kids Shorts',
    color: '#A3BBAD',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Comfortable #A3BBAD shorts for kids.',
    type: 'Shorts',
    category: 'Kids',
    price: 12.99,
    fabric: 'Cotton Blend',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Elastic waist', 'Machine washable'],
    availableColors: ['#A3BBAD', '#000000', '#ABC4AB'],
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: 3,
    name: 'Kids Hoodie',
    color: '#ACF39D',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Warm #ACF39D hoodie for kids.',
    type: 'Hoodie',
    category: 'Kids',
    price: 25.99,
    fabric: 'Fleece',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Hooded', 'Front pocket'],
    availableColors: ['#ACF39D', '#983628', '#A3BBAD'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 4,
    name: 'Kids Jacket',
    color: '#983628',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Stylish #983628 jacket for kids.',
    type: 'Jacket',
    category: 'Kids',
    price: 35.99,
    fabric: 'Polyester',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Water-resistant', 'Zip-up'],
    availableColors: ['#983628', '#A3BBAD', '#000000'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 5,
    name: 'Kids Jeans',
    color: '#000000',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Durable #000000 jeans for kids.',
    type: 'Jeans',
    category: 'Kids',
    price: 22.99,
    fabric: 'Denim',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Stretchable', 'Machine washable'],
    availableColors: ['#000000', '#A3BBAD'],
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: 6,
    name: 'Kids Dress',
    color: '#DCC9B6',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Cute #DCC9B6 dress for girls.',
    type: 'Dress',
    category: 'Kids',
    price: 18.99,
    fabric: 'Cotton',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Lightweight', 'Comfortable'],
    availableColors: ['#DCC9B6', '#EDE580', '#F4F4F9'],
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: 7,
    name: 'Kids Sweater',
    color: '#F4F4F9',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Cozy #F4F4F9 sweater for kids.',
    type: 'Sweater',
    category: 'Kids',
    price: 20.99,
    fabric: 'Wool',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Warm', 'Soft'],
    availableColors: ['#F4F4F9', '#ABC4AB', '#A3BBAD'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 8,
    name: 'Kids Sneakers',
    color: '#ABC4AB',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Comfortable #ABC4AB sneakers for kids.',
    type: 'Shoes',
    category: 'Kids',
    price: 29.99,
    fabric: 'Synthetic',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Non-slip sole', 'Breathable'],
    availableColors: ['#ABC4AB', '#000000', '#F4F4F9'],
    sizes: ['10', '11', '12', '13']
  },
  {
    id: 9,
    name: 'Kids Hat',
    color: 'Orange',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Bright orange hat for kids.',
    type: 'Hat',
    category: 'Kids',
    price: 10.99,
    fabric: 'Cotton',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Adjustable strap', 'Breathable'],
    availableColors: ['Orange', '#EDE580', '#A3BBAD'],
    sizes: ['S', 'M', 'L']
  },
  {
    id: 10,
    name: 'Kids Pajamas',
    color: '#5E4955',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Soft #5E4955 pajamas for kids.',
    type: 'Pajamas',
    category: 'Kids',
    price: 19.99,
    fabric: 'Cotton',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Soft', 'Comfortable'],
    availableColors: ['#5E4955', '#DCC9B6', '#A3BBAD'],
    sizes: ['XS', 'S', 'M', 'L']
  },
  // Ladies Clothes
  {
    id: 11,
    name: 'Ladies Blouse',
    color: '#F4F4F9',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Elegant #F4F4F9 blouse for ladies.',
    type: 'Blouse',
    category: 'Women',
    price: 30.99,
    fabric: 'Silk',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Soft', 'Breathable'],
    availableColors: ['#F4F4F9', '#000000', '#A3BBAD'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 12,
    name: 'Ladies Skirt',
    color: '#000000',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Chic #000000 skirt for ladies.',
    type: 'Skirt',
    category: 'Women',
    price: 25.99,
    fabric: 'Polyester',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Stretchable', 'Comfortable'],
    availableColors: ['#000000', '#983628', '#ABC4AB'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 13,
    name: 'Ladies Dress',
    color: '#983628',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Stunning #983628 dress for ladies.',
    type: 'Dress',
    category: 'Women',
    price: 40.99,
    fabric: 'Silk',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Elegant', 'Soft'],
    availableColors: ['#983628', '#000000', '#A3BBAD'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 14,
    name: 'Ladies Jacket',
    color: '#A3BBAD',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Stylish #A3BBAD jacket for ladies.',
    type: 'Jacket',
    category: 'Women',
    price: 50.99,
    fabric: 'Leather',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Water-resistant', 'Warm'],
    availableColors: ['#A3BBAD', '#000000', '#6D4C3D'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 15,
    name: 'Ladies Jeans',
    color: '#2F4550',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Comfortable #2F4550 jeans for ladies.',
    type: 'Jeans',
    category: 'Women',
    price: 35.99,
    fabric: 'Denim',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Stretchable', 'Durable'],
    availableColors: ['#2F4550', '#000000', '#A3BBAD'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 16,
    name: 'Ladies Sweater',
    color: '#ABC4AB',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Cozy #ABC4AB sweater for ladies.',
    type: 'Sweater',
    category: 'Women',
    price: 28.99,
    fabric: 'Wool',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Warm', 'Soft'],
    availableColors: ['#ABC4AB', '#F4F4F9', '#000000'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 17,
    name: 'Ladies T-Shirt',
    color: '#DCC9B6',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Casual #DCC9B6 t-shirt for ladies.',
    type: 'T-Shirt',
    category: 'Women',
    price: 18.99,
    fabric: 'Cotton',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Breathable', 'Machine washable'],
    availableColors: ['#DCC9B6', '#F4F4F9', '#A3BBAD'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 18,
    name: 'Ladies Shorts',
    color: '#EBCBF4',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Comfortable #EBCBF4 shorts for ladies.',
    type: 'Shorts',
    category: 'Women',
    price: 22.99,
    fabric: 'Cotton Blend',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Elastic waist', 'Machine washable'],
    availableColors: ['#EBCBF4', '#000000', '#ABC4AB'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 19,
    name: 'Ladies Shoes',
    color: '#6D4C3D',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Stylish #6D4C3D shoes for ladies.',
    type: 'Shoes',
    category: 'Women',
    price: 45.99,
    fabric: 'Leather',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Comfortable', 'Durable'],
    availableColors: ['#6D4C3D', '#000000', '#ABC4AB'],
    sizes: ['5', '6', '7', '8']
  },
  {
    id: 20,
    name: 'Ladies Hat',
    color: '#EDE580',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Trendy #EDE580 hat for ladies.',
    type: 'Hat',
    category: 'Women',
    price: 12.99,
    fabric: 'Cotton',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Adjustable strap', 'Breathable'],
    availableColors: ['#EDE580', '#983628', '#A3BBAD'],
    sizes: ['S', 'M', 'L']
  },
  // Men Clothes
  {
    id: 21,
    name: 'Men T-Shirt',
    color: '#000000',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Classic #000000 t-shirt for men.',
    type: 'T-Shirt',
    category: 'Men',
    price: 18.99,
    fabric: 'Cotton',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Breathable', 'Machine washable'],
    availableColors: ['#000000', '#F4F4F9', '#ABC4AB'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 22,
    name: 'Men Jeans',
    color: '#A3BBAD',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Comfortable #A3BBAD jeans for men.',
    type: 'Jeans',
    category: 'Men',
    price: 32.99,
    fabric: 'Denim',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Stretchable', 'Durable'],
    availableColors: ['#A3BBAD', '#000000'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 23,
    name: 'Men Hoodie',
    color: '#ABC4AB',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Warm #ABC4AB hoodie for men.',
    type: 'Hoodie',
    category: 'Men',
    price: 25.99,
    fabric: 'Fleece',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Hooded', 'Front pocket'],
    availableColors: ['#ABC4AB', '#000000', '#A3BBAD'],
    sizes: ['M', 'L', 'XL', 'XXL']
  },
  {
    id: 24,
    name: 'Men Jacket',
    color: '#6D4C3D',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Stylish #6D4C3D jacket for men.',
    type: 'Jacket',
    category: 'Men',
    price: 50.99,
    fabric: 'Leather',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Water-resistant', 'Warm'],
    availableColors: ['#6D4C3D', '#000000', '#ABC4AB'],
    sizes: ['M', 'L', 'XL', 'XXL']
  },
  {
    id: 25,
    name: 'Men Suit',
    color: '#2F4550',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Elegant #2F4550 suit for men.',
    type: 'Suit',
    category: 'Men',
    price: 120.99,
    fabric: 'Wool Blend',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Elegant', 'Comfortable'],
    availableColors: ['#2F4550', '#000000', '#ABC4AB'],
    sizes: ['M', 'L', 'XL', 'XXL']
  },
  {
    id: 26,
    name: 'Men Sweater',
    color: '#ACF39D',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Cozy #ACF39D sweater for men.',
    type: 'Sweater',
    category: 'Men',
    price: 28.99,
    fabric: 'Wool',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Warm', 'Soft'],
    availableColors: ['#ACF39D', '#ABC4AB', '#000000'],
    sizes: ['M', 'L', 'XL', 'XXL']
  },
  {
    id: 27,
    name: 'Men Shorts',
    color: '#A39171',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Casual #A39171 shorts for men.',
    type: 'Shorts',
    category: 'Men',
    price: 22.99,
    fabric: 'Cotton Blend',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Elastic waist', 'Comfortable'],
    availableColors: ['#A39171', '#000000', '#A3BBAD'],
    sizes: ['M', 'L', 'XL', 'XXL']
  },
  {
    id: 28,
    name: 'Men Shoes',
    color: '#000000',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Stylish #000000 shoes for men.',
    type: 'Shoes',
    category: 'Men',
    price: 55.99,
    fabric: 'Leather',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Durable', 'Comfortable'],
    availableColors: ['#000000', '#6D4C3D', '#ABC4AB'],
    sizes: ['9', '10', '11', '12']
  },
  {
    id: 29,
    name: 'Men Hat',
    color: '#A3BBAD',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Trendy #A3BBAD hat for men.',
    type: 'Hat',
    category: 'Men',
    price: 15.99,
    fabric: 'Cotton',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Adjustable strap', 'Breathable'],
    availableColors: ['#A3BBAD', '#000000', '#ABC4AB'],
    sizes: ['M', 'L', 'XL']
  },
  {
    id: 30,
    name: 'Men Belt',
    color: '#6D4C3D',
    imageUrl: './../../../../assets/sackcloth-sackcloth-textured-laptop-ipad.jpg',
    description: 'It looks like you have. If you need further assistance or want to modify this structure, feel free to ask!Classic #6D4C3D belt for men.',
    type: 'Belt',
    category: 'Men',
    price: 19.99,
    fabric: 'Leather',
    features: ['Adjustable strap', 'Breathable', 'Lightweight', 'Sun protection','Adjustable', 'Durable'],
    availableColors: ['#6D4C3D', '#000000'],
    sizes: ['S', 'M', 'L', 'XL']
  }
];
